### 만들기
POST http://localhost:8080/v1/post/create
Content-Type: application/json
Authorization: {{authorizationHeader}}

{
  "title": "테스트 제목",
  "author": "test",
  "content": "테스트 내용",
  "password": "test"
}

### 선택한 게시글 조회
GET http://localhost:8080/v1/post/1
Content-Type: application/json
Authorization: {{authorizationHeader}}
